app:
  name: order-api
  namespace: cesi-eats
  image:
    repository: ghcr.io/cesi-eats/order_api
    tag: latest

dependencies:
  lapinou:
    uri: amqp://rabbitmq-service.cesi-eats.svc.cluster.local:5672

  database:
    uri: mongodb://armanddebesse.fr:27017/order_db

commission:
  cesieats: 5
  deliveryman: 5